DevelopFixes
TanyaStk/Lab2.Matrix pull request #1
Opened 2020-09-11 12:19 UTC by TanyaStk

2020-09-17 21:55 UTC, VeronikaYastr requested changes

2020-09-17 21:55 UTC, VeronikaYastr commented on src/main/java/com/project1/Main.java
> +            if (row == 0 | column == 0) {
Обычно используют логическое ||. Просто | побитово сравнивает, не думаю, что здесь это имеет какой-то смысл)

2020-09-17 21:55 UTC, VeronikaYastr commented on src/test/java/com/project1/MainTest.java
> +public class MainTest {
Не получились тесты?😔

2020-09-17 21:56 UTC, TanyaStk commented on src/test/java/com/project1/MainTest.java
> +public class MainTest {
Я в процессе)

2020-09-17 21:57 UTC, VeronikaYastr commented on src/test/java/com/project1/MainTest.java
> +public class MainTest {
А,  хорошо))
Ну я их тогда завтра уже посмотрю😴

2020-09-20 16:45 UTC, VeronikaYastr commented
Все хорошо, можно мержить)

2020-09-21 19:01 UTC, merged